---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cartservice
spec:
  selector:
    matchLabels:
      app: cartservice
  template:
    metadata:
      labels:
        app: cartservice
    spec:
      containers:
        - name: service
          image: gcr.io/google-samples/microservices-demo/cartservice:v0.3.6
          resources:
            limits:
              memory: '64Mi'
              cpu: '250m'
          ports:
            - containerPort: 7070
          env:
            - name: PORT
              value: '7070'
            - name: REDIS_ADDR
              value: 'redis-cart:6379'

---
apiVersion: v1
kind: Service
metadata:
  name: cartservice
spec:
  selector:
    app: cartservice
  ports:
    - port: 7070
      targetPort: 7070
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-cart
spec:
  selector:
    matchLabels:
      app: redis-cart
  template:
    metadata:
      labels:
        app: redis-cart
    spec:
      containers:
        - name: redis
          image: redis:alpine
          ports:
            - containerPort: 6379
          resources:
            requests:
              cpu: 200m
              memory: 64Mi
            limits:
              cpu: 300m
              memory: 128Mi
          # readinessProbe:
          #   initialDelaySeconds: 15
          #   exec:
          #     command:
          #       ['/bin/grpc_health_probe', '-addr=:7070', '-rpc-timeout=5s']
          # livenessProbe:
          #   initialDelaySeconds: 15
          #   periodSeconds: 10
          #   exec:
          #     command:
          #       ['/bin/grpc_health_probe', '-addr=:7070', '-rpc-timeout=5s']
          volumeMounts:
            - name: redis-data
              mountPath: /data
      volumes:
        - name: redis-data
          emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: redis-cart
spec:
  selector:
    app: redis-cart
  ports:
    - port: 6379
      targetPort: 6379
