---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: currencyservice
spec:
  selector:
    matchLabels:
      app: currencyservice
  template:
    metadata:
      labels:
        app: currencyservice
    spec:
      containers:
        - name: service
          image: gcr.io/google-samples/microservices-demo/currencyservice:v0.3.6
          resources:
            limits:
              memory: '64Mi'
              cpu: '250m'
          ports:
            - containerPort: 7000
          env:
            - name: PORT
              value: '7000'
            - name: DISABLE_TRACING
              value: '1'
            - name: DISABLE_PROFILER
              value: '1'
            - name: DISABLE_DEBUGGER
              value: '1'
---
apiVersion: v1
kind: Service
metadata:
  name: currencyservice
spec:
  selector:
    app: currencyservice
  ports:
    - port: 7000
      targetPort: 7000
