---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: emailservice
spec:
  selector:
    matchLabels:
      app: emailservice
  template:
    metadata:
      labels:
        app: emailservice
    spec:
      containers:
        - name: service
          image: gcr.io/google-samples/microservices-demo/emailservice:v0.3.6
          resources:
            limits:
              memory: '64Mi'
              cpu: '250m'
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              value: '8080'
            - name: DISABLE_TRACING
              value: '1'
            - name: DISABLE_PROFILER
              value: '1'
            - name: DISABLE_DEBUGGER
              value: '1'
---
apiVersion: v1
kind: Service
metadata:
  name: emailservice
spec:
  selector:
    app: emailservice
  ports:
    - port: 8080
      targetPort: 8080
