---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: service
          image: gcr.io/google-samples/microservices-demo/frontend:v0.3.6
          resources:
            limits:
              memory: '64Mi'
              cpu: '250m'
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              value: '8080'
            - name: DISABLE_TRACING
              value: '1'
            - name: DISABLE_PROFILER
              value: '1'
            - name: DISABLE_DEBUGGER
              value: '1'
            - name: PRODUCT_CATALOG_SERVICE_ADDR
              value: 'productcatalogservice:3550'
            - name: SHIPPING_SERVICE_ADDR
              value: 'shippingservice:50051'
            - name: CURRENCY_SERVICE_ADDR
              value: 'currencyservice:7000'
            - name: PAYMENT_SERVICE_ADDR
              value: 'paymentservice:50051'
            - name: CHECKOUT_SERVICE_ADDR
              value: 'checkoutservice:5050'
            - name: CART_SERVICE_ADDR
              value: 'cartservice:7070'
            - name: AD_SERVICE_ADDR
              value: 'adservice:9555'
            - name: RECOMMENDATION_SERVICE_ADDR
              value: 'recommendationservice:8080'
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  selector:
    app: frontend
  ports:
    - port: 80
      targetPort: 8080
