---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: paymentservice
spec:
  selector:
    matchLabels:
      app: paymentservice
  template:
    metadata:
      labels:
        app: paymentservice
    spec:
      containers:
        - name: service
          image: gcr.io/google-samples/microservices-demo/paymentservice:v0.3.6
          resources:
            limits:
              memory: '64Mi'
              cpu: '250m'
          ports:
            - containerPort: 50051
          env:
            - name: PORT
              value: '50051'
            - name: DISABLE_TRACING
              value: '1'
            - name: DISABLE_PROFILER
              value: '1'
            - name: DISABLE_DEBUGGER
              value: '1'
---
apiVersion: v1
kind: Service
metadata:
  name: paymentservice
spec:
  selector:
    app: paymentservice
  ports:
    - port: 50051
      targetPort: 50051
