---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: productcatalogservice
spec:
  selector:
    matchLabels:
      app: productcatalogservice
  template:
    metadata:
      labels:
        app: productcatalogservice
    spec:
      containers:
        - name: service
          image: gcr.io/google-samples/microservices-demo/productcatalogservice:v0.3.6
          resources:
            limits:
              memory: '64Mi'
              cpu: '250m'
          ports:
            - containerPort: 3550
          env:
            - name: PORT
              value: '3550'
---
apiVersion: v1
kind: Service
metadata:
  name: productcatalogservice
spec:
  selector:
    app: productcatalogservice
  ports:
    - port: 3550
      targetPort: 3550
